# global configs
Global:
  checkpoints: null
  pretrained_model: null
  output_dir: ./output/
  device: cpu
  save_interval: 1
  eval_during_train: True
  eval_interval: 1
  epochs: 6
  print_batch_step: 10
  use_visualdl: False
  # used for static mode and model export
  image_shape: [3, 224, 224]
  save_inference_dir: ./inference

# model architecture
Arch:
  name: ResNet18
  num_classes: 2
 
# loss function config for traing/eval process
Loss:
  name: CrossEntropyLoss
  # weight: 1.0

Optimizer:
  name: SGD
  momentum: 0.9
  weight_decay: 0.0005
  lr: 0.1

Scheduler:
  name: StepLR
  step_size: 30
  gamma: 0.1


# data loader for train and eval
DataLoader:
  Train:
    dataset:
      name: ImageNetDataset
      image_root: ./datasets/cat_dog_cls/images/
      cls_label_path: ./datasets/cat_dog_cls/train.txt
      transform_ops:
        - Pad:
            padding: 224
        - RandomCrop:
            size: 224
        - RandomHorizontalFlip:
            p: 0.5
        - ToTensor: None
        - Normalize:
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            inplace: False
    sampler:
      name: DistributedBatchSampler
      batch_size: 2
      drop_last: False
      shuffle: True
    loader:
      num_workers: 0
      use_shared_memory: True

  Eval:
    dataset: 
      name: ImageNetDataset
      image_root: ./datasets/cat_dog_cls/images/
      cls_label_path: D:/python_workspace/boreas/common_model_application/datasets/cat_dog_cls/train.txt
      transform_ops:
        - ResizeImage:
            resize_short: 256
        - CropImage:
            size: 224
        - NormalizeImage:
            scale: 1.0/255.0
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ''
    sampler:
      name: DistributedBatchSampler
      batch_size: 2
      drop_last: False
      shuffle: False
    loader:
      num_workers: 0
      use_shared_memory: True

Infer:
  infer_imgs: docs/images/inference_deployment/whl_demo.jpg
  batch_size: 10
  transforms:
    - DecodeImage:
        to_rgb: True
        channel_first: False
    - ResizeImage:
        resize_short: 256
    - CropImage:
        size: 224
    - NormalizeImage:
        scale: 1.0/255.0
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
        order: ''
    - ToCHWImage:
  PostProcess:
    name: Topk
    topk: 5
    class_id_map_file: ppcls/utils/imagenet1k_label_list.txt

Metric:
    name: TopK
    topk: [1, 2]
